name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-unit-tests
  cancel-in-progress: true

jobs:
  unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run build

