name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'



jobs:
  unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run test
      - run: npm run build

